name: volt
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0+2
  provider: ^5.0.0
  get_it: ^7.1.3
  flutter_svg: ^0.23.0+1
  google_fonts: ^2.1.0
  pin_code_fields: ^7.3.0
  country_code_picker: ^2.0.2
  iconly: ^1.0.1
  equatable: ^2.0.3
  connectivity: ^3.0.6
  flutter_credit_card: ^3.0.1
  flutter_slidable: ^1.1.0
  logger: ^1.0.0
  dartz: ^0.10.0-nullsafety.2
  flutter_dotenv: ^5.0.0
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^4.2.0
  dio:
    git: 
      url: https://github.com/Space-HQ/dio.git
      path: dio/

  pretty_dio_logger:
    git:
      url: https://github.com/Space-HQ/pretty_dio_logger.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/volt_logo/
    - assets/images/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
