// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS9ut8yovEAHwp7UsYcz_BwWUy5uQBhzI',
    appId: '1:858082998268:web:2e9242f9510fceb6be6479',
    messagingSenderId: '858082998268',
    projectId: 'volt-456cd',
    authDomain: 'volt-456cd.firebaseapp.com',
    storageBucket: 'volt-456cd.appspot.com',
    measurementId: 'G-2EXBLD7L3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6wG07Za9f6CfRGT4K5-cSqRdh5Cn7lWc',
    appId: '1:858082998268:android:4e5fabea9a84b2bcbe6479',
    messagingSenderId: '858082998268',
    projectId: 'volt-456cd',
    storageBucket: 'volt-456cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMrwbpuftNs63S6-ZrMZTDlsW5DXV6VHg',
    appId: '1:858082998268:ios:5f2708db7d19634ebe6479',
    messagingSenderId: '858082998268',
    projectId: 'volt-456cd',
    storageBucket: 'volt-456cd.appspot.com',
    iosClientId: '858082998268-qijreua7qkg11s5bhppv60bpchnes3oj.apps.googleusercontent.com',
    iosBundleId: 'com.volt.laundry',
  );
}
